# Generated by Django 3.2.21 on 2023-10-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20230808_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name of the user', max_length=300, null=True),
        ),
    ]
