# Generated by Django 3.2.21 on 2023-10-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_userprofile_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='organization_name',
            new_name='organization',
        ),
    ]
